version: '3'
services:
  crawler:
    build: .
    env_file:
      - /opt/projects/fx/env.env
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/projects/fx:/code/
    restart: always
    container_name: "crawler"


networks:
  default:
    external:
      name: fxservice_default
