FROM python:alpine3.6
MAINTAINER [nbhoa]
ENV LANG=C.UTF-8

RUN apk add --no-cache bash git
COPY ./requirements.txt /
RUN pip3 install -r /requirements.txt

ENTRYPOINT  pip3 install -e /code/fxclient && cd /code/crawler/crawler &&  python3 synchronizer.py