version: '3'
services:
  crawler:
    build: .
    env_file:
      - /opt/projects/fx/env.env
    volumes:
      - /fx/oanda_data/log:/logs
      - /opt/projects/fx:/code/
    stdin_open: true
    restart: always
    container_name: "crawler"


networks:
  default:
    external:
      name: fxservice_default
