version: '3'
services:
  data-service:
    build: /opt/projects/fx/data-service
    volumes:
      - /fx/log:/fx/logs
      - /opt/projects/fx/data-service:/code/
      - /etc/localtime:/etc/localtime
    stdin_open: true
    tty: true
    links:
      - influxdb
    depends_on:
      - influxdb
    container_name: "data-service"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      - /fx/db:/var/lib/influxdb
