FROM python:alpine3.6
ENV LANG=C.UTF-8

RUN apk add --no-cache bash git
COPY ./requirements.txt /
RUN pip3 install -r /requirements.txt

ENTRYPOINT  pip3 install -e /code/fxclient && cd /code/strategy/strategy &&  python3 execute_task.py