version: '3'
services:
  fxservice:
    build: .
    volumes:
      - /opt/projects/fx/fxservice/fxservice:/code/
    env_file:
      - /opt/projects/fx/env.env
    restart: always
    ports:
      - "9000:9000"
    environment:
      host: "influxdb"
    links:
      - influxdb
    depends_on:
      - influxdb
    container_name: "fxservice"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      - /fx/db:/var/lib/influxdb
