FROM sgoblin/python3.5:latest
MAINTAINER [nbhoa]
ENV LANG=C.UTF-8

# install pip3
RUN apt-get -y install python3-pip && pip3 install --upgrade pip


COPY ./requirements.txt /
RUN pip3 install -r /requirements.txt

ENTRYPOINT  cd /code/data-service/ &&  python3 server.py